language: node_js
node_js:
  - "5.7.0"
script:
  - "npm update"
  - "node node_modules/kindscript/built/kind.js buildtarget"
  - "node node_modules/kindscript/built/kind.js uploadtrg microbit-latest"  
  - "node node_modules/kindscript/built/kind.js uploaddoc"
sudo: false
notifications:
  email:
    - touchdevelop-build@microsoft.com
cache:
  directories:
    - node_modules

