language: node_js
node_js:
  - "5.7.0"
script:
  - "node node_modules/pxt-core/built/pxt.js travis"  
  - "(cd libs/lang-test0; node ../../node_modules/pxt-core/built/pxt.js run)"
  - "node node_modules/pxt-core/built/pxt.js uploaddoc"
sudo: false
notifications:
  email:
    - touchdevelop-build@microsoft.com
cache:
  directories:
    - node_modules

